//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using YudianBlog.Infrastructure.Domain;
using YudianBlog.Model.Comment;
using YudianBlog.Model.Post;

namespace YudianBlog.Model.User
{
    public class UserInfo:EntityBase<int>,IAggregateRoot
    {
        /// <summary>
        /// 用户Id
        /// </summary>
        public virtual int User_id
        {
            get;
            set;
        }

        /// <summary>
        /// 用户电邮地址
        /// </summary>
        public virtual string User_email
        {
            get;
            set;
        }

        /// <summary>
        /// 用户昵称
        /// </summary>
        public virtual string User_nicename
        {
            get;
            set;
        }

        /// <summary>
        /// 密码Salt值
        /// </summary>
        public virtual string User_salt
        {
            get;
            set;
        }

        /// <summary>
        /// 用户密码
        /// </summary>
        public virtual string User_pass
        {
            get;
            set;
        }

        /// <summary>
        /// 用户的注册名称
        /// </summary>
        public virtual string User_login
        {
            get;
            set;
        }

        /// <summary>
        /// 用户注册时间
        /// </summary>
        public virtual DateTime User_registeredtime
        {
            get;
            set;
        }

        /// <summary>
        /// 用户状态
        /// </summary>
        public virtual int User_status
        {
            get;
            set;
        }

        /// <summary>
        /// 用户网址
        /// </summary>
        public virtual string User_url
        {
            get;
            set;
        }


        /// <summary>
        /// 用户表-用户额外属性表
        /// </summary>
        public virtual IEnumerable<UserMetaInfo> UserMetaInfo
        {
            get;
            set;
        }

        /// <summary>
        /// 用户表-文章表
        /// </summary>
        public virtual IEnumerable<PostInfo> PostInfo
        {
            get;
            set;
        }

        ///// <summary>
        ///// 用户表-评论表
        ///// </summary>
        //public virtual IEnumerable<CommentInfo> CommentInfo
        //{
        //    get;
        //    set;
        //}

        protected override void Validate()
        {
            throw new NotImplementedException();
        }
    }

}