//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using YudianBlog.Infrastructure.Domain;

namespace YudianBlog.Model.User
{
    /// <summary>
    /// 用户额外属性
    /// </summary>
    public class UserMetaInfo : EntityBase<int>
    {
        /// <summary>
        /// UserMeta_id
        /// </summary>
        public virtual int UserMeta_id
        {
            get;
            set;
        }

        /// <summary>
        /// 用户Id
        /// </summary>
        public virtual int Users_id
        {
            get;
            set;
        }

        /// <summary>
        /// UserMete_key
        /// </summary>
        public virtual string UserMeta_key
        {
            get;
            set;
        }

        /// <summary>
        /// UserMeta_value
        /// </summary>
        public virtual string UserMeta_value
        {
            get;
            set;
        }

        /// <summary>
        /// 用户表-用户额外属性表
        /// </summary>
        public virtual UserInfo UserInfo
        {
            get;
            set;
        }

        protected override void Validate()
        {
            throw new NotImplementedException();
        }
    }
}
