//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using YudianBlog.Infrastructure.Domain;

namespace YudianBlog.Model.Comment
{

    /// <summary>
    /// 文章额外属性
    /// </summary>
    public class CommentMetaInfo : EntityBase<int>
    {
        /// <summary>
        /// CommentMateId
        /// </summary>
        public virtual int CommentMeta_id
        {
            get;
            set;
        }

        /// <summary>
        /// 评论Id
        /// </summary>
        public virtual int Comments_id
        {
            get;
            set;
        }

        /// <summary>
        /// CommentMete_key
        /// </summary>
        public virtual string CommentMeta_key
        {
            get;
            set;
        }

        /// <summary>
        /// CommentMeta_value
        /// </summary>
        public virtual string CommentMeta_value
        {
            get;
            set;
        }

        /// <summary>
        /// 评论表
        /// </summary>
        public virtual CommentInfo CommentInfo
        {
            get;
            set;
        }

        protected override void Validate()
        {
            throw new NotImplementedException();
        }
    }
}
