//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using YudianBlog.Infrastructure.Domain;
using YudianBlog.Model.Post;
using YudianBlog.Model.User;

namespace YudianBlog.Model.Comment
{
    /// <summary>
    /// 评论表
    /// </summary>
    public class CommentInfo : EntityBase<int>, IAggregateRoot
    {
        /// <summary>
        /// 每个评论的唯一ID号
        /// </summary>
        public virtual int Comment_id
        {
            get;
            set;
        }

        /// <summary>
        ///  某一评论对应的用户ID，只有当用户注册后才会生成，对应yd_users.ID。未注册的用户，即外部评论者，这个ID的值为0
        /// </summary>
        public virtual int Comment_user_id
        {
            get;
            set;
        }

        /// <summary>
        /// 每个评论的评论者的客户端信息，主要包括其浏览器和操作系统的类型、版本等资料。
        /// </summary>
        public virtual string Comment_agent
        {
            get;
            set;
        }

        /// <summary>
        /// 每个评论的当前状态
        /// </summary>
        public virtual CommentApproved Comment_approved
        {
            get;
            set;
        }

        /// <summary>
        /// 每个评论的具体内容
        /// </summary>
        public virtual string Comment_content
        {
            get;
            set;
        }

        /// <summary>
        /// 每个评论发表的时间
        /// </summary>
        public virtual DateTime Comment_date
        {
            get;
            set;
        }

        /// <summary>
        /// 每个评论的评论者的IP地址
        /// </summary>
        public virtual string Comment_author_ip
        {
            get;
            set;
        }

        /// <summary>
        /// 每个评论的评论者网址
        /// </summary>
        public virtual string Comment_author_url
        {
            get;
            set;
        }

        /// <summary>
        /// 每个评论对应的文章的ID号
        /// </summary>
        public virtual object Comment_post_id
        {
            get;
            set;
        }

        /// <summary>
        /// 父评论ID
        /// </summary>
        public virtual int Comment_parent
        {
            get;
            set;
        }

        /// <summary>
        /// 每个评论的评论者名称
        /// </summary>
        public virtual string Comment_author
        {
            get;
            set;
        }

        /// <summary>
        /// 每个评论的评论者电邮地址
        /// </summary>
        public virtual string Comment_author_email
        {
            get;
            set;
        }

        /// <summary>
        /// 评论表-评论额外属性表
        /// </summary>
        public virtual IEnumerable<CommentMetaInfo> CommentMetaInfo
        {
            get;
            set;
        }

        /// <summary>
        /// 文章表
        /// </summary>
        public virtual PostInfo PostInfo
        {
            get;
            set;
        }

        ///// <summary>
        ///// 用户表-评论表
        ///// </summary>
        //public virtual UserInfo UserInfo
        //{
        //    get;
        //    set;
        //}

        protected override void Validate()
        {
            throw new NotImplementedException();
        }
    }
}
