//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace YudianBlog.Model.Post
{
    /// <summary>
    /// 文章当前的状态
    /// </summary>
    public enum PostStatus
    {
        /// <summary>
        /// 公开
        /// </summary>
        open = 1,

        /// <summary>
        /// 草稿
        /// </summary>
        draft = 3,

        /// <summary>
        /// 私人
        /// </summary>
        close = 2,
    }
}