//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using YudianBlog.Infrastructure.Domain;

namespace YudianBlog.Model.Post
{
    /// <summary>
    /// 文章额外属性
    /// </summary>
    public class PostMetaInfo : EntityBase<int>
    {
        /// <summary>
        /// PostMateId
        /// </summary>
        public virtual int PostMeta_id
        {
            get;
            set;
        }

        /// <summary>
        /// 文章Id
        /// </summary>
        public virtual int Posts_id
        {
            get;
            set;
        }

        /// <summary>
        /// PostMete_key
        /// </summary>
        public virtual string PostMeta_key
        {
            get;
            set;
        }

        /// <summary>
        /// PostMeta_value
        /// </summary>
        public virtual string PostMeta_value
        {
            get;
            set;
        }

        /// <summary>
        /// 文章表-文章额外属性表
        /// </summary>
        public virtual PostInfo PostInfo
        {
            get;
            set;
        }

        protected override void Validate()
        {
            throw new NotImplementedException();
        }
    }

}