//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace YudianBlog.Model.Post
{
    /// <summary>
    /// 评论设置的状态
    /// </summary>
    public enum PostCommentStatus
    {
        /// <summary>
        /// 允许评论
        /// </summary>
        open = 1,

        /// <summary>
        /// 不允许评论
        /// </summary>
        close = 2,

        /// <summary>
        /// 只有注册用户方可评论
        /// </summary>
        regstered = 3,
    }
}
