//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace YudianBlog.Model.Category
{
    public enum CategoryType
    {
        /// <summary>
        /// 文章
        /// </summary>
        post = 1,

        /// <summary>
        /// 链接
        /// </summary>
        link = 2,

        /// <summary>
        /// 标签
        /// </summary>
        tag = 3,
    }
}