//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using YudianBlog.Infrastructure.Domain;

namespace YudianBlog.Model.Option
{
    /// <summary>
    /// 存储WordPress系统选项和插件、主题配置
    /// </summary>
    public class OptionInfo : EntityBase<int>, IAggregateRoot
    {
        /// <summary>
        /// 设置表Id
        /// </summary>
        public virtual int Option_id
        {
            get;
            set;
        }

        /// <summary>
        /// 是否自动加载(默认1)
        /// </summary>
        public virtual int Option_autoload
        {
            get;
            set;
        }

        /// <summary>
        /// Option_name
        /// </summary>
        public virtual string Option_name
        {
            get;
            set;
        }

        /// <summary>
        /// Option_value
        /// </summary>
        public virtual string Option_value
        {
            get;
            set;
        }

        protected override void Validate()
        {
            throw new NotImplementedException();
        }
    }
}

